#pragma once

template <class T>
class CProxy_IAuStageEvents : public IConnectionPointImpl<T, &__uuidof(_IAuStageEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
